export const BUILDING_TYPES = {
  TOWN_HALL: {
    id: "town-hall",
    name: "Town Hall",
    label: "TH",
    cost: 320,
    color: 0xd97706,
    textureKey: "town",
    fallbackTextureKeys: ["command-center", "machine-wood"],
    bodyHeight: 68,
    roofHeight: 20,
    footprintRows: 2,
    footprintCols: 2,
  },
  WOOD_MACHINE: {
    id: "wood-machine",
    name: "Wood Machine",
    label: "WM",
    cost: 240,
    color: 0xb45309,
    shopImage: "/assets/machine-wood.png",
    fallbackShopImages: ["/assets/command center.png", "/assets/town.png"],
    textureKey: "machine-wood",
    fallbackTextureKeys: ["command-center", "town"],
    bodyHeight: 46,
    roofHeight: 14,
    footprintRows: 1,
    footprintCols: 1,
  },
  COMMAND_CENTER: {
    id: "command-center",
    name: "Command Center",
    label: "TH",
    cost: 1800,
    color: 0x334155,
    shopImage: "/assets/command center.png",
    fallbackShopImages: ["/assets/town.png", "/assets/machine-wood.png"],
    textureKey: "command-center",
    fallbackTextureKeys: ["town", "machine-wood"],
    bodyHeight: 84,
    roofHeight: 22,
    footprintRows: 1,
    footprintCols: 1,
  },
  SKYPORT: {
    id: "skyport",
    name: "Chopper Bay",
    label: "SP",
    cost: 2000,
    color: 0x64748b,
    shopImage: "/assets/chopper/skychop.png",
    fallbackShopImages: ["/assets/command center.png", "/assets/town.png"],
    textureKey: "skyport-empty",
    fallbackTextureKeys: ["skyport-shop", "command-center", "town"],
    bodyHeight: 64,
    roofHeight: 18,
    footprintRows: 2,
    footprintCols: 2,
  },
  BATTLE_TANK: {
    id: "battle-tank",
    name: "Battle Tank",
    label: "BT",
    cost: 1500,
    color: 0x64748b,
    shopImage: "/assets/tank/tank1.png",
    fallbackShopImages: ["/assets/command center.png", "/assets/machine-wood.png"],
    textureKey: "tank-owned",
    fallbackTextureKeys: ["tank-shop", "command-center", "machine-wood"],
    bodyHeight: 42,
    roofHeight: 12,
    footprintRows: 1,
    footprintCols: 1,
  },
  AIR_DEFENSE: {
    id: "air-defense",
    name: "Air Defense",
    label: "AD",
    cost: 5000,
    color: 0x475569,
    shopImage: "/assets/airdef.png",
    fallbackShopImages: ["/assets/command center.png", "/assets/town.png"],
    textureKey: "air-defense",
    fallbackTextureKeys: ["command-center", "town"],
    bodyHeight: 72,
    roofHeight: 18,
    footprintRows: 1,
    footprintCols: 1,
  },
  TENT: {
    id: "tent",
    name: "Soldier Tent",
    label: "TN",
    cost: 1000,
    color: 0x78716c,
    shopImage: "/assets/tent.png",
    fallbackShopImages: ["/assets/machine-wood.png", "/assets/town.png"],
    textureKey: "tent",
    fallbackTextureKeys: ["machine-wood", "town"],
    bodyHeight: 54,
    roofHeight: 16,
    footprintRows: 1,
    footprintCols: 1,
  },
};

export const BUILDING_LIST = Object.values(BUILDING_TYPES).filter((building) => building.id !== "town-hall");

export const getBuildingUpgradeCost = (buildingTypeOrId) => {
  const buildingType = typeof buildingTypeOrId === "string"
    ? BUILDING_LIST.find((item) => item.id === buildingTypeOrId)
    : buildingTypeOrId;

  return Math.max(0, Number(buildingType?.cost ?? 0) * 3);
};
