export const BUILDING_TYPES = {
  TOWN_HALL: {
    id: "town-hall",
    name: "Town Hall",
    label: "TH",
    cost: 320,
    color: 0xd97706,
    bodyHeight: 68,
    roofHeight: 20,
    footprintRows: 2,
    footprintCols: 2,
  },
  GOLD_STORGE: {
    id: "gold-storage",
    name: "Gold Storage",
    label: "GS",
    cost: 180,
    color: 0xeab308,
    bodyHeight: 56,
    roofHeight: 18,
  },
  ELIXIR_HUT: {
    id: "elixir-hut",
    name: "Elixir Hut",
    label: "EH",
    cost: 160,
    color: 0xdb2777,
    bodyHeight: 52,
    roofHeight: 18,
  },
  CANNON: {
    id: "cannon",
    name: "Cannon",
    label: "CA",
    cost: 220,
    color: 0x475569,
    bodyHeight: 44,
    roofHeight: 14,
  },
  ARCHER_TOWER: {
    id: "archer-tower",
    name: "Archer Tower",
    label: "AT",
    cost: 260,
    color: 0x16a34a,
    bodyHeight: 76,
    roofHeight: 20,
  },
  BARRACKS: {
    id: "barracks",
    name: "Barracks",
    label: "BA",
    cost: 200,
    color: 0x0284c7,
    bodyHeight: 58,
    roofHeight: 18,
  },
};

export const BUILDING_LIST = Object.values(BUILDING_TYPES);
